"""Ingestion pipeline tests -- generated by REVIEW.

Closes coverage_report.md gaps 1 and 6: `IngestionPipeline` is the single writer
every event in the system passes through, and it had no test at all. Its broad
`except Exception` (ingestion.py:209) is also what hides a persistence failure
from every other layer, which is how finding F-1 survived the original suite.

## Status: NOT EXECUTED

Written during a review session in which `pytest` was denied by the permission
gate. Nothing here has been run.

Three tests below are expected to FAIL until F-1 is fixed. They are the
regression tests for it and are deliberately not skipped:

    test_second_batch_for_an_existing_session_persists
    test_session_window_widens_across_separate_batches
    test_session_end_in_a_later_batch_sets_duration

F-1: `_upsert_session` compares an aware `event.timestamp` against
`row.start_time`/`row.end_time` read back from SQLite. SQLite returns naive
datetimes, so the comparison raises TypeError on any batch that reloads an
existing session row -- i.e. every batch after a session's first. The fix is to
read through `backend.database.session.as_utc`, as every API router already does.
"""

from __future__ import annotations

import asyncio
from datetime import datetime, timedelta, timezone

import pytest
from sqlalchemy import select

from backend.database.models import Command, Event, Session
from backend.database.session import as_utc, session_scope
from backend.shared.events import EventType, UniversalEvent
from backend.shared.timeutil import utcnow
from backend.telemetry.ingestion import IngestionPipeline, persist_events
from backend.telemetry.watcher_status import registry


def _event(session_id="s1", event=EventType.FILE_MODIFIED, timestamp=None, **kwargs):
    defaults = dict(
        session_id=session_id,
        timestamp=timestamp if timestamp is not None else utcnow(),
        agent="claude",
        event=event,
        file="backend/app.py",
        metadata={"lines_added": 3, "lines_removed": 1},
        source="hook",
    )
    defaults.update(kwargs)
    return UniversalEvent(**defaults)


class _StubAdapter:
    """Minimal stand-in for ClaudeAdapter's pipeline-facing surface."""

    def __init__(self, cost: float = 0.0, cost_raises: bool = False) -> None:
        self._cost = cost
        self._cost_raises = cost_raises

    def estimate_cost(self, event: UniversalEvent) -> float:
        if self._cost_raises:
            raise RuntimeError("pricing table exploded")
        if event.event is EventType.RESPONSE_RECEIVED:
            return self._cost
        return 0.0


def _run_pipeline(adapter, events) -> None:
    """Submit `events` through a real pipeline and shut it down cleanly."""

    async def _main() -> None:
        # Constructed inside the loop: the queue belongs to this loop.
        pipeline = IngestionPipeline(adapter)
        pipeline.start()
        for event in events:
            await pipeline.submit(event)
        await pipeline.stop()

    asyncio.run(_main())


# -- F-1 regression: writes that cross a transaction boundary ---------------


def test_second_batch_for_an_existing_session_persists():
    """REGRESSION (F-1): the second batch reloads the row from SQLite.

    The first `persist_events` call constructs the Session row in Python, so its
    datetimes stay timezone-aware for the whole transaction. The second call
    opens a new `session_scope`, so `db.get` issues a real SELECT and gets naive
    datetimes back -- and `_upsert_session` compares them against an aware
    timestamp.

    In production this is not a test-only edge: the queue tailer polls once a
    second, so the second batch arrives roughly one second into every session.
    Every event after the first is silently dropped.
    """
    start = utcnow()
    persist_events([_event(timestamp=start)])
    persist_events([_event(timestamp=start + timedelta(minutes=1))])

    with session_scope() as db:
        events = db.execute(select(Event)).scalars().all()

    assert len(events) == 2, "the second batch was dropped -- see finding F-1"


def test_session_window_widens_across_separate_batches():
    """REGRESSION (F-1): out-of-order arrival across two transactions.

    The two data sources are independent, so a transcript record can legitimately
    describe a moment earlier than the hook event already written.
    """
    later = utcnow()
    earlier = later - timedelta(minutes=20)

    persist_events([_event(timestamp=later)])
    persist_events([_event(timestamp=earlier)])

    with session_scope() as db:
        row = db.get(Session, "s1")
        assert row is not None
        drift = abs((as_utc(row.start_time) - earlier).total_seconds())

    assert drift < 1.0, "start_time did not widen backwards -- see finding F-1"


def test_session_end_in_a_later_batch_sets_duration():
    """REGRESSION (F-1): SESSION_ENDED almost always arrives in its own batch."""
    start = utcnow()
    persist_events(
        [_event(event=EventType.SESSION_STARTED, timestamp=start, file=None, metadata={})]
    )
    persist_events(
        [
            _event(
                event=EventType.SESSION_ENDED,
                timestamp=start + timedelta(minutes=30),
                file=None,
                metadata={},
            )
        ]
    )

    with session_scope() as db:
        row = db.get(Session, "s1")
        assert row is not None
        assert row.end_time is not None, "session never recorded an end -- see F-1"
        assert row.duration == pytest.approx(1800, abs=2)


def test_many_sequential_batches_all_persist():
    """The realistic shape: one event per poll cycle, many cycles."""
    start = utcnow()
    for minute in range(10):
        persist_events([_event(timestamp=start + timedelta(minutes=minute))])

    with session_scope() as db:
        assert len(db.execute(select(Event)).scalars().all()) == 10


# -- as_utc, the helper F-1 forgot to call ---------------------------------


def test_as_utc_attaches_utc_to_a_naive_datetime():
    naive = datetime(2026, 1, 15, 10, 0, 0)
    assert as_utc(naive) == datetime(2026, 1, 15, 10, 0, 0, tzinfo=timezone.utc)


def test_as_utc_normalizes_an_aware_datetime_and_passes_none_through():
    aware = datetime(2026, 1, 15, 10, 0, 0, tzinfo=timezone(timedelta(hours=5)))
    assert as_utc(aware) == datetime(2026, 1, 15, 5, 0, 0, tzinfo=timezone.utc)
    assert as_utc(None) is None


# -- IngestionPipeline: queue -> writer -> database -------------------------


def test_pipeline_persists_everything_submitted():
    events = [
        _event(event=EventType.SESSION_STARTED, file=None, metadata={}),
        _event(),
        _event(
            event=EventType.TERMINAL_COMMAND,
            file=None,
            metadata={"command": "pytest -q", "exit_code": 0},
        ),
    ]
    _run_pipeline(_StubAdapter(), events)

    with session_scope() as db:
        assert len(db.execute(select(Event)).scalars().all()) == 3
        command = db.execute(select(Command)).scalar_one()
        assert command.command == "pytest -q"


def test_pipeline_drains_the_queue_before_stopping():
    """`stop()` must flush, not discard -- it runs in FastAPI's lifespan teardown."""
    events = [_event(timestamp=utcnow() + timedelta(seconds=i)) for i in range(25)]
    _run_pipeline(_StubAdapter(), events)

    with session_scope() as db:
        assert len(db.execute(select(Event)).scalars().all()) == 25


def test_a_failing_batch_does_not_kill_the_writer(monkeypatch):
    """The isolation guarantee: a persistence fault must not stop ingestion.

    Without this, one bad batch would silently end all collection while the app
    kept reporting itself healthy.
    """
    import backend.telemetry.ingestion as ingestion_module

    attempts: list[int] = []

    def exploding_persist(events, costs=None):
        batch = list(events)
        attempts.append(len(batch))
        raise RuntimeError("disk full")

    monkeypatch.setattr(ingestion_module, "persist_events", exploding_persist)

    # Must not raise: the failure is contained inside the writer coroutine.
    _run_pipeline(_StubAdapter(), [_event(), _event()])

    assert attempts, "the writer never attempted the batch"


def test_a_failing_batch_is_reported_to_the_user(monkeypatch):
    """PRD section 25 requires a telemetry failure to be visible in the UI.

    Both watchers report health into `WatcherRegistry`, which `/stats` serves and
    the Home page renders. The writer now does too (review_report.md F-2 fix in
    IngestionPipeline._run), so a persistence failure surfaces as "degraded"
    instead of the dashboard silently showing "watchers running" while data is
    discarded.
    """
    import backend.telemetry.ingestion as ingestion_module

    def exploding_persist(events, costs=None):
        raise RuntimeError("disk full")

    monkeypatch.setattr(ingestion_module, "persist_events", exploding_persist)
    registry.clear()

    _run_pipeline(_StubAdapter(), [_event()])

    snapshot = registry.snapshot()
    degraded = [name for name, health in snapshot.items() if health["status"] == "degraded"]
    assert degraded, "a persistence failure was not surfaced to the UI"


def test_cost_estimator_failure_does_not_lose_the_event():
    """A broken pricing table must cost the dollar figure, not the telemetry."""
    _run_pipeline(
        _StubAdapter(cost_raises=True),
        [
            _event(
                event=EventType.RESPONSE_RECEIVED,
                file=None,
                model="claude-sonnet-4-5",
                metadata={"token_count": 100, "input_tokens": 80, "output_tokens": 20},
                source="transcript",
            )
        ],
    )

    with session_scope() as db:
        row = db.get(Session, "s1")
        assert row is not None
        assert row.token_count == 100
        assert row.estimated_cost == 0.0


def test_cost_is_accumulated_onto_the_session():
    _run_pipeline(
        _StubAdapter(cost=0.25),
        [
            _event(
                event=EventType.RESPONSE_RECEIVED,
                file=None,
                model="claude-sonnet-4-5",
                metadata={"token_count": 100, "input_tokens": 80, "output_tokens": 20},
                source="transcript",
            )
        ],
    )

    with session_scope() as db:
        row = db.get(Session, "s1")
        assert row is not None
        assert row.estimated_cost == pytest.approx(0.25)


def test_stopping_a_pipeline_that_never_started_is_safe():
    async def _main():
        pipeline = IngestionPipeline(_StubAdapter())
        await pipeline.stop()

    asyncio.run(_main())


def test_poison_event_skips_only_itself(temp_home):
    """One unpersistable event must not abort its batch-mates."""
    good_start = _event(session_id="s-poison", event=EventType.SESSION_STARTED)
    good_end = _event(session_id="s-poison", event=EventType.SESSION_ENDED)
    # Garbage line counts blow up int() inside _write_file_record.
    poison = _event(
        session_id="s-poison",
        event=EventType.FILE_MODIFIED,
        metadata={"lines_added": "not-a-number"},
    )

    written = persist_events([good_start, poison, good_end])

    assert written == 2
    with session_scope() as db:
        rows = db.execute(select(Event).where(Event.session_id == "s-poison")).all()
        assert len(rows) == 2
