"""Watcher, reader and offset-store tests -- generated by REVIEW.

Closes coverage_report.md gaps 2, 3, 4 and 6. Before this file,
`queue_tailer.py`, `transcript_poller.py`, `transcript_reader.py` and
`offsets.py` had **no tests at all** -- roughly 190 statements of the most
failure-sensitive logic in the codebase:

* the partial-line / byte-offset arithmetic, where an off-by-one silently
  duplicates or destroys every subsequent record, and
* the persisted offset store, where a mis-save re-ingests from byte 0 and
  double-counts every session aggregate.

## Status: NOT EXECUTED

Written during a review session in which `pytest` was denied by the permission
gate. Nothing here has been run.

The two `run()`-loop tests use a short real sleep to let one poll cycle
complete. If they prove flaky on a loaded machine, raise `_CYCLE_SECONDS` rather
than deleting them -- the error-isolation guarantee they check (PRD section 25)
is a stated product requirement with no other coverage.
"""

from __future__ import annotations

import asyncio
import json
from pathlib import Path

from backend.adapters.claude import transcript_reader
from backend.adapters.claude.adapter import ClaudeAdapter
from backend.shared import paths
from backend.telemetry import queue_tailer, transcript_poller
from backend.telemetry.offsets import OffsetStore
from backend.telemetry.queue_tailer import QueueTailer, read_new_lines
from backend.telemetry.transcript_poller import TranscriptPoller
from backend.telemetry.watcher_status import registry

#: Long enough for one poll cycle (which offloads to a real thread) to finish.
_CYCLE_SECONDS = 0.5


def _append_json_lines(path: Path, *records) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("ab") as handle:
        for record in records:
            handle.write((json.dumps(record) + "\n").encode("utf-8"))


def _append_raw(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("ab") as handle:
        handle.write(text.encode("utf-8"))


class _CollectingPipeline:
    """Stands in for IngestionPipeline; records what the watcher submitted."""

    def __init__(self) -> None:
        self.events: list = []

    async def submit(self, event) -> None:
        self.events.append(event)


# ==========================================================================
# queue_tailer.read_new_lines
# ==========================================================================


def test_reads_complete_lines_and_advances_the_offset(tmp_path):
    queue = tmp_path / "claude_hooks.jsonl"
    _append_json_lines(queue, {"a": 1}, {"b": 2})

    records, offset = read_new_lines(queue, 0)

    assert records == [{"a": 1}, {"b": 2}]
    assert offset == queue.stat().st_size


def test_a_partial_final_line_is_left_for_the_next_cycle(tmp_path):
    """The hook handler may be mid-append; consuming a half-written line would
    corrupt the offset and therefore every record after it."""
    queue = tmp_path / "claude_hooks.jsonl"
    _append_json_lines(queue, {"a": 1})
    complete_size = queue.stat().st_size
    _append_raw(queue, '{"b": 2')  # no trailing newline

    records, offset = read_new_lines(queue, 0)

    assert records == [{"a": 1}]
    assert offset == complete_size, "offset advanced past an incomplete line"


def test_the_partial_line_is_read_once_it_is_completed(tmp_path):
    queue = tmp_path / "claude_hooks.jsonl"
    _append_json_lines(queue, {"a": 1})
    _append_raw(queue, '{"b": 2')

    _, offset = read_new_lines(queue, 0)
    _append_raw(queue, "}\n")
    records, final_offset = read_new_lines(queue, offset)

    assert records == [{"b": 2}]
    assert final_offset == queue.stat().st_size


def test_resuming_from_an_offset_returns_only_new_records(tmp_path):
    queue = tmp_path / "claude_hooks.jsonl"
    _append_json_lines(queue, {"a": 1})
    _, offset = read_new_lines(queue, 0)

    _append_json_lines(queue, {"b": 2})
    records, _ = read_new_lines(queue, offset)

    assert records == [{"b": 2}], "already-ingested records were re-read"


def test_no_new_bytes_returns_nothing(tmp_path):
    queue = tmp_path / "claude_hooks.jsonl"
    _append_json_lines(queue, {"a": 1})
    _, offset = read_new_lines(queue, 0)

    assert read_new_lines(queue, offset) == ([], offset)


def test_a_missing_queue_file_is_not_an_error(tmp_path):
    """A machine that has never run a hook is a normal, supported state."""
    assert read_new_lines(tmp_path / "nope.jsonl", 0) == ([], 0)


def test_a_shrunken_file_restarts_from_zero(tmp_path):
    """Truncation or rotation: reading from a stale offset would be meaningless."""
    queue = tmp_path / "claude_hooks.jsonl"
    _append_json_lines(queue, {"a": 1}, {"b": 2})
    stale_offset = queue.stat().st_size

    queue.write_bytes(b'{"c": 3}\n')
    records, offset = read_new_lines(queue, stale_offset)

    assert records == [{"c": 3}]
    assert offset == queue.stat().st_size


def test_a_malformed_line_is_skipped_without_losing_the_rest(tmp_path):
    """PRD user story 3: one bad line must not cost us the file."""
    queue = tmp_path / "claude_hooks.jsonl"
    _append_json_lines(queue, {"a": 1})
    _append_raw(queue, "this is not json at all\n")
    _append_json_lines(queue, {"b": 2})

    records, offset = read_new_lines(queue, 0)

    assert records == [{"a": 1}, {"b": 2}]
    assert offset == queue.stat().st_size, "the skipped line must still be consumed"


def test_non_object_json_lines_are_ignored(tmp_path):
    queue = tmp_path / "claude_hooks.jsonl"
    _append_json_lines(queue, [1, 2, 3], "a string", {"a": 1})

    records, _ = read_new_lines(queue, 0)

    assert records == [{"a": 1}]


def test_blank_lines_are_ignored(tmp_path):
    queue = tmp_path / "claude_hooks.jsonl"
    _append_raw(queue, "\n\n")
    _append_json_lines(queue, {"a": 1})

    records, _ = read_new_lines(queue, 0)

    assert records == [{"a": 1}]


# ==========================================================================
# transcript_reader
# ==========================================================================


def test_discover_transcripts_on_a_missing_directory_returns_empty(tmp_path):
    """A machine with no Claude Code install must not raise."""
    assert transcript_reader.discover_transcripts(tmp_path / "absent") == []


def test_discover_transcripts_finds_nested_jsonl_files(tmp_path):
    root = tmp_path / "projects"
    (root / "proj-a").mkdir(parents=True)
    (root / "proj-b" / "nested").mkdir(parents=True)
    (root / "proj-a" / "one.jsonl").write_text("", encoding="utf-8")
    (root / "proj-b" / "nested" / "two.jsonl").write_text("", encoding="utf-8")
    (root / "proj-a" / "ignore.txt").write_text("", encoding="utf-8")

    found = transcript_reader.discover_transcripts(root)

    assert [p.name for p in found] == ["one.jsonl", "two.jsonl"]


def test_read_new_records_returns_complete_records_and_offset(tmp_path):
    path = tmp_path / "session.jsonl"
    _append_json_lines(path, {"type": "assistant"}, {"type": "user"})

    batch = transcript_reader.read_new_records(path, 0)

    assert batch.records == [{"type": "assistant"}, {"type": "user"}]
    assert batch.new_offset == path.stat().st_size
    assert batch.path == path


def test_read_new_records_holds_back_a_partial_line(tmp_path):
    """Claude Code appends while we read; a torn tail must be re-read, not lost."""
    path = tmp_path / "session.jsonl"
    _append_json_lines(path, {"type": "assistant"})
    complete_size = path.stat().st_size
    _append_raw(path, '{"type": "assi')

    batch = transcript_reader.read_new_records(path, 0)

    assert batch.records == [{"type": "assistant"}]
    assert batch.new_offset == complete_size


def test_read_new_records_restarts_when_the_file_shrinks(tmp_path):
    path = tmp_path / "session.jsonl"
    _append_json_lines(path, {"type": "assistant"})
    stale = path.stat().st_size + 500

    batch = transcript_reader.read_new_records(path, stale)

    assert batch.records == [{"type": "assistant"}]


def test_read_new_records_skips_malformed_lines(tmp_path):
    path = tmp_path / "session.jsonl"
    _append_raw(path, "{ not json\n")
    _append_json_lines(path, {"type": "assistant"})

    batch = transcript_reader.read_new_records(path, 0)

    assert batch.records == [{"type": "assistant"}]


def test_read_new_records_on_a_missing_file_returns_the_offset_unchanged(tmp_path):
    batch = transcript_reader.read_new_records(tmp_path / "gone.jsonl", 42)

    assert batch.records == []
    assert batch.new_offset == 42


# ==========================================================================
# OffsetStore
# ==========================================================================


def test_offsets_round_trip_through_disk(tmp_path):
    path = tmp_path / "tailer_state.json"

    store = OffsetStore(path)
    store.set("/logs/claude_hooks.jsonl", 512)
    store.save()

    reloaded = OffsetStore(path)
    reloaded.load()

    assert reloaded.get("/logs/claude_hooks.jsonl") == 512


def test_an_unknown_key_starts_at_zero(tmp_path):
    store = OffsetStore(tmp_path / "state.json")
    store.load()

    assert store.get("/never/seen.jsonl") == 0


def test_a_missing_state_file_loads_as_empty(tmp_path):
    store = OffsetStore(tmp_path / "absent.json")
    store.load()  # must not raise

    assert store.get("anything") == 0


def test_a_corrupt_state_file_starts_fresh_rather_than_raising(tmp_path):
    """Restarting from 0 duplicates events -- recoverable. Crashing the watcher
    on a corrupt cache file is not."""
    path = tmp_path / "state.json"
    path.write_text("{ this is not json", encoding="utf-8")

    store = OffsetStore(path)
    store.load()

    assert store.get("anything") == 0


def test_non_numeric_offset_values_are_dropped(tmp_path):
    path = tmp_path / "state.json"
    path.write_text(json.dumps({"good": 10, "bad": "not a number"}), encoding="utf-8")

    store = OffsetStore(path)
    store.load()

    assert store.get("good") == 10
    assert store.get("bad") == 0


def test_save_is_a_noop_when_nothing_changed(tmp_path):
    path = tmp_path / "state.json"
    store = OffsetStore(path)
    store.load()
    store.save()

    assert not path.exists(), "a clean store should not write"


def test_save_force_writes_even_when_clean(tmp_path):
    path = tmp_path / "state.json"
    store = OffsetStore(path)
    store.load()
    store.save(force=True)

    assert path.is_file()


def test_setting_the_same_offset_twice_does_not_redirty(tmp_path):
    path = tmp_path / "state.json"
    store = OffsetStore(path)
    store.set("a", 5)
    store.save()
    path.unlink()

    store.set("a", 5)
    store.save()

    assert not path.exists(), "an unchanged offset should not trigger a rewrite"


def test_save_leaves_no_temp_file_behind(tmp_path):
    path = tmp_path / "state.json"
    store = OffsetStore(path)
    store.set("a", 1)
    store.save()

    assert list(tmp_path.glob("*.tmp")) == []


# ==========================================================================
# Watcher loops: error isolation (PRD section 25)
# ==========================================================================


def _run_one_cycle_then_snapshot(watcher):
    """Let a watcher run one poll cycle, then snapshot health and cancel.

    The snapshot is taken *before* cancelling because cancellation marks the
    watcher `stopped`, which would overwrite the status under test.
    """

    async def _main():
        task = asyncio.create_task(watcher.run())
        await asyncio.sleep(_CYCLE_SECONDS)
        snapshot = registry.snapshot()
        task.cancel()
        try:
            await task
        except asyncio.CancelledError:
            pass
        except Exception:  # noqa: BLE001 -- teardown only
            pass
        return snapshot

    return asyncio.run(_main())


def test_queue_tailer_submits_mapped_events(temp_home):
    queue = paths.hook_queue_path()
    _append_json_lines(
        queue,
        {
            "session_id": "sess-1",
            "hook_event_name": "SessionStart",
            "_received_at": 1767225600.0,
        },
    )

    pipeline = _CollectingPipeline()
    tailer = QueueTailer(ClaudeAdapter(), pipeline, OffsetStore(tmp_state(temp_home)), queue)
    _run_one_cycle_then_snapshot(tailer)

    assert len(pipeline.events) == 1
    assert pipeline.events[0].session_id == "sess-1"


def test_queue_tailer_reports_itself_degraded_and_keeps_running(temp_home, monkeypatch):
    """A failing cycle must degrade this watcher only -- never propagate."""

    def exploding_read(path, offset):
        raise OSError("queue file is on fire")

    monkeypatch.setattr(queue_tailer, "read_new_lines", exploding_read)

    tailer = QueueTailer(
        ClaudeAdapter(), _CollectingPipeline(), OffsetStore(tmp_state(temp_home))
    )
    snapshot = _run_one_cycle_then_snapshot(tailer)

    assert snapshot[queue_tailer.NAME]["status"] == "degraded"
    assert "queue file is on fire" in snapshot[queue_tailer.NAME]["last_error"]


def test_queue_tailer_reports_healthy_on_a_clean_cycle(temp_home):
    paths.hook_queue_path().parent.mkdir(parents=True, exist_ok=True)

    tailer = QueueTailer(
        ClaudeAdapter(), _CollectingPipeline(), OffsetStore(tmp_state(temp_home))
    )
    snapshot = _run_one_cycle_then_snapshot(tailer)

    assert snapshot[queue_tailer.NAME]["status"] == "running"


def test_transcript_poller_skips_one_unreadable_file_and_continues(temp_home, monkeypatch):
    """One broken transcript must not cost us the other sessions'."""
    root = paths.claude_transcript_root()
    (root / "proj").mkdir(parents=True, exist_ok=True)
    bad = root / "proj" / "bad.jsonl"
    good = root / "proj" / "good.jsonl"
    bad.write_text("", encoding="utf-8")
    _append_json_lines(
        good,
        {
            "type": "assistant",
            "sessionId": "sess-good",
            "message": {
                "model": "claude-sonnet-4-5",
                "usage": {"input_tokens": 10, "output_tokens": 5},
            },
        },
    )

    real_read = transcript_reader.read_new_records

    def selective_read(path, offset=0):
        if Path(path).name == "bad.jsonl":
            raise OSError("permission denied")
        return real_read(path, offset)

    monkeypatch.setattr(transcript_reader, "read_new_records", selective_read)

    pipeline = _CollectingPipeline()
    poller = TranscriptPoller(ClaudeAdapter(), pipeline, OffsetStore(tmp_state(temp_home)))
    snapshot = _run_one_cycle_then_snapshot(poller)

    assert [e.session_id for e in pipeline.events] == ["sess-good"]
    assert snapshot[transcript_poller.NAME]["status"] == "running"


def test_transcript_poller_is_healthy_with_no_transcripts_at_all(temp_home):
    """No Claude Code install is a supported state, not a degraded one."""
    poller = TranscriptPoller(
        ClaudeAdapter(), _CollectingPipeline(), OffsetStore(tmp_state(temp_home))
    )
    snapshot = _run_one_cycle_then_snapshot(poller)

    assert snapshot[transcript_poller.NAME]["status"] == "running"


def tmp_state(home: Path) -> Path:
    """Offset file inside the test's temp home, never the developer's cache."""
    return home / "cache" / "tailer_state.json"
