"""Hook installer tests -- generated by REVIEW.

Closes coverage_report.md gap 5. `scripts/install_claude_hooks.py` is the
highest-blast-radius code in this repository -- it rewrites the user's real
`~/.claude/settings.json` -- and it had no tests and had never been executed.

Its safety properties (back up, merge rather than overwrite, idempotent, refuse
invalid JSON, atomic replace) are stated in the module docstring and were, until
now, entirely unverified. The `[UNVERIFIED]` hook schema makes a re-run likely,
which makes idempotency and foreign-hook preservation the two properties most
worth pinning down.

Every test here operates on a `tmp_path` settings file. **No test touches the
developer's real `~/.claude/`.**

## Status: NOT EXECUTED

Written during a review session in which `pytest` was denied by the permission
gate. Nothing here has been run.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parent.parent
_SCRIPT = _REPO_ROOT / "scripts" / "install_claude_hooks.py"


def _load_installer():
    """Load the script by path.

    `scripts/` is not in `pyproject.toml`'s wheel packages, so it may not be
    importable as `scripts.install_claude_hooks` in an installed-package layout.
    Loading by file path works either way.
    """
    spec = importlib.util.spec_from_file_location("_installer_under_test", _SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


installer = _load_installer()

COMMAND = '"/usr/bin/python3" "/repo/backend/adapters/claude/hook_handler.py"'
FOREIGN = {"hooks": [{"type": "command", "command": "/other/tool/notify.sh"}]}


def _settings_with_foreign_hook() -> dict:
    return {
        "model": "claude-opus-5",
        "permissions": {"allow": ["Bash(git:*)"]},
        "hooks": {"PreToolUse": [dict(FOREIGN)]},
    }


# -- install ----------------------------------------------------------------


def test_install_into_empty_settings_adds_every_hook_event():
    settings, added = installer.install({}, COMMAND)

    assert added == len(installer.HOOK_EVENTS)
    assert set(settings["hooks"]) == set(installer.HOOK_EVENTS)


def test_installed_entries_carry_the_command():
    settings, _ = installer.install({}, COMMAND)

    entry = settings["hooks"]["SessionStart"][0]
    assert entry["hooks"][0] == {"type": "command", "command": COMMAND}


def test_tool_use_events_get_a_wildcard_matcher():
    """PreToolUse/PostToolUse filter by tool; the adapter decides what matters,
    so filtering here would only hide data from it."""
    settings, _ = installer.install({}, COMMAND)

    for event in ("PreToolUse", "PostToolUse"):
        assert settings["hooks"][event][0]["matcher"] == "*"


def test_non_tool_events_get_no_matcher():
    settings, _ = installer.install({}, COMMAND)

    for event in ("SessionStart", "UserPromptSubmit", "Stop", "SessionEnd"):
        assert "matcher" not in settings["hooks"][event][0]


def test_install_is_idempotent():
    """Re-running must not duplicate entries -- a duplicated hook would double
    every event the queue file receives."""
    settings, first = installer.install({}, COMMAND)
    settings, second = installer.install(settings, COMMAND)

    assert first == len(installer.HOOK_EVENTS)
    assert second == 0
    for event in installer.HOOK_EVENTS:
        assert len(settings["hooks"][event]) == 1


def test_install_is_idempotent_even_if_the_interpreter_path_changed():
    """Entries are matched by the `hook_handler.py` marker, not the whole
    command, so a rebuilt venv does not produce a second registration."""
    settings, _ = installer.install({}, COMMAND)
    settings, added = installer.install(
        settings, '"/other/venv/bin/python" "/repo/backend/adapters/claude/hook_handler.py"'
    )

    assert added == 0


def test_install_preserves_unrelated_settings():
    settings, _ = installer.install(_settings_with_foreign_hook(), COMMAND)

    assert settings["model"] == "claude-opus-5"
    assert settings["permissions"] == {"allow": ["Bash(git:*)"]}


def test_install_preserves_another_tools_hooks():
    """Read-modify-write, never regenerate: someone else's hooks must survive."""
    settings, _ = installer.install(_settings_with_foreign_hook(), COMMAND)

    pre = settings["hooks"]["PreToolUse"]
    assert FOREIGN in pre
    assert len(pre) == 2


def test_install_refuses_a_non_object_hooks_value():
    with pytest.raises(SystemExit):
        installer.install({"hooks": "not an object"}, COMMAND)


def test_install_skips_an_event_whose_value_is_not_a_list():
    """Malformed single event: skip it, do not destroy it."""
    settings, added = installer.install({"hooks": {"Stop": "bogus"}}, COMMAND)

    assert settings["hooks"]["Stop"] == "bogus"
    assert added == len(installer.HOOK_EVENTS) - 1


# -- uninstall --------------------------------------------------------------


def test_uninstall_removes_exactly_what_install_added():
    settings, _ = installer.install({}, COMMAND)
    settings, removed = installer.uninstall(settings)

    assert removed == len(installer.HOOK_EVENTS)
    assert "hooks" not in settings


def test_uninstall_leaves_another_tools_hooks_intact():
    settings, _ = installer.install(_settings_with_foreign_hook(), COMMAND)
    settings, _ = installer.uninstall(settings)

    assert settings["hooks"]["PreToolUse"] == [FOREIGN]
    assert settings["model"] == "claude-opus-5"


def test_uninstall_leaves_no_empty_hook_lists():
    settings, _ = installer.install({"hooks": {"PreToolUse": [dict(FOREIGN)]}}, COMMAND)
    settings, _ = installer.uninstall(settings)

    assert list(settings["hooks"]) == ["PreToolUse"]


def test_uninstall_on_clean_settings_changes_nothing():
    original = _settings_with_foreign_hook()
    settings, removed = installer.uninstall(_settings_with_foreign_hook())

    assert removed == 0
    assert settings == original


def test_install_uninstall_round_trips_to_the_original():
    original = _settings_with_foreign_hook()
    settings, _ = installer.install(_settings_with_foreign_hook(), COMMAND)
    settings, _ = installer.uninstall(settings)

    assert settings == original


# -- load_settings ----------------------------------------------------------


def test_load_settings_on_a_missing_file_is_empty(tmp_path):
    assert installer.load_settings(tmp_path / "settings.json") == {}


def test_load_settings_on_an_empty_file_is_empty(tmp_path):
    path = tmp_path / "settings.json"
    path.write_text("   \n", encoding="utf-8")

    assert installer.load_settings(path) == {}


def test_load_settings_refuses_invalid_json(tmp_path):
    """Overwriting an unparseable settings file would destroy the user's whole
    Claude Code configuration. Refusing is the only safe behaviour."""
    path = tmp_path / "settings.json"
    path.write_text('{"model": "opus",,,}', encoding="utf-8")

    with pytest.raises(SystemExit):
        installer.load_settings(path)


def test_load_settings_refuses_a_non_object_document(tmp_path):
    path = tmp_path / "settings.json"
    path.write_text("[1, 2, 3]", encoding="utf-8")

    with pytest.raises(SystemExit):
        installer.load_settings(path)


# -- write_settings ---------------------------------------------------------


def test_write_settings_backs_up_an_existing_file(tmp_path):
    path = tmp_path / "settings.json"
    path.write_text(json.dumps({"model": "original"}), encoding="utf-8")

    installer.write_settings(path, {"model": "replaced"})

    backup = tmp_path / "settings.json.bak"
    assert backup.is_file()
    assert json.loads(backup.read_text(encoding="utf-8")) == {"model": "original"}
    assert json.loads(path.read_text(encoding="utf-8")) == {"model": "replaced"}


def test_write_settings_creates_parent_directories(tmp_path):
    path = tmp_path / "nested" / ".claude" / "settings.json"

    installer.write_settings(path, {"model": "x"})

    assert path.is_file()


def test_write_settings_leaves_no_temp_file(tmp_path):
    path = tmp_path / "settings.json"

    installer.write_settings(path, {"model": "x"})

    assert list(tmp_path.glob("*.tmp")) == []


def test_write_settings_does_not_back_up_a_file_that_did_not_exist(tmp_path):
    path = tmp_path / "settings.json"

    installer.write_settings(path, {"model": "x"})

    assert not (tmp_path / "settings.json.bak").exists()


# -- main() -----------------------------------------------------------------


def test_dry_run_writes_nothing(tmp_path, monkeypatch):
    path = tmp_path / "settings.json"
    monkeypatch.setattr(installer, "settings_path", lambda project: path)

    assert installer.main(["--dry-run"]) == 0
    assert not path.exists(), "--dry-run must not touch the settings file"


def test_main_installs_with_yes_and_is_then_a_noop(tmp_path, monkeypatch):
    path = tmp_path / "settings.json"
    monkeypatch.setattr(installer, "settings_path", lambda project: path)

    assert installer.main(["--yes"]) == 0
    written = json.loads(path.read_text(encoding="utf-8"))
    assert set(written["hooks"]) == set(installer.HOOK_EVENTS)

    # Second run: already in the desired state, nothing to do.
    assert installer.main(["--yes"]) == 0
    assert json.loads(path.read_text(encoding="utf-8")) == written


def test_main_uninstall_round_trips(tmp_path, monkeypatch):
    path = tmp_path / "settings.json"
    path.write_text(json.dumps({"model": "keep-me"}, indent=2), encoding="utf-8")
    monkeypatch.setattr(installer, "settings_path", lambda project: path)

    installer.main(["--yes"])
    installer.main(["--yes", "--uninstall"])

    assert json.loads(path.read_text(encoding="utf-8")) == {"model": "keep-me"}


def test_hook_command_points_at_a_real_handler_file():
    """A registered command that does not exist would fail silently on every
    hook, and the user's only symptom would be an empty dashboard."""
    assert installer.handler_path().is_file()
    assert "hook_handler.py" in installer.hook_command()
    assert installer.MARKER in installer.hook_command()
